import { Project, Task } from "./types";

export const seedProjects: Project[] = [
  { id: "p1", name: "Design Homepage", priority: "high", lead: "Dexter", dueDate: "2026-09-12" },
  { id: "p2", name: "Develop Login Feature", priority: "low", lead: "CN", dueDate: "2026-09-15" },
  { id: "p3", name: "Test Payment Gateway", priority: "medium", dueDate: "2026-09-18" },
];

export const seedTasks: Task[] = [
  {
    id: "t1",
    title: "Write API Documentation",
    description:
      "Create clear and detailed API documentation to guide developers in using the inventory and sales metrics features effectively.",
    status: "todo",
    priority: "high",
    labels: ["Research", "Design", "Development", "Testing", "Deployment"],
    startDate: "2026-01-10",
    dueDate: "2026-07-31",
    member: "Admin",
    team: "Engineering",
    reporter: "Dexter",
    projectId: "p1",
    subtasks: [
      { id: "s1", title: "Subtask 1", priority: "high", member: "Dexter", dueDate: "2026-09-12" },
      { id: "s2", title: "Subtask 2", priority: "low", member: "CN", dueDate: "2026-09-15" },
      { id: "s3", title: "Subtask 3", priority: "medium", dueDate: "2026-09-18" },
    ],
    comments: [
      { id: "c1", author: "Ankit Dutta", text: "dsds", createdAt: "just now" },
    ],
    createdAt: "2026-07-20",
  },
  {
    id: "t2",
    title: "Implement Search Function",
    status: "todo",
    priority: "medium",
    labels: ["Deployment", "Deployment"],
    dueDate: "2026-07-29",
    member: "Admin",
    projectId: "p1",
    subtasks: [],
    comments: [],
    createdAt: "2026-07-20",
  },
  {
    id: "t3",
    title: "Deploy to Production",
    status: "todo",
    priority: "urgent",
    labels: ["Deployment", "Deployment"],
    dueDate: "2026-07-29",
    member: "Admin",
    projectId: "p1",
    subtasks: [],
    comments: [],
    createdAt: "2026-07-20",
  },
  {
    id: "t4",
    title: "Code Review Completed",
    status: "doing",
    priority: "medium",
    labels: ["Deployment", "Deployment"],
    dueDate: "2026-07-29",
    member: "Admin",
    projectId: "p2",
    subtasks: [],
    comments: [],
    createdAt: "2026-07-18",
  },
  {
    id: "t5",
    title: "Design Mockups Finalized",
    status: "doing",
    priority: "low",
    labels: ["Deployment", "Deployment"],
    dueDate: "2026-07-29",
    member: "Admin",
    projectId: "p2",
    subtasks: [],
    comments: [],
    createdAt: "2026-07-18",
  },
  {
    id: "t6",
    title: "Feature Testing Passed",
    status: "completed",
    priority: "medium",
    labels: ["Testing", "Passed"],
    dueDate: "2026-07-30",
    member: "QA Team",
    projectId: "p3",
    subtasks: [],
    comments: [],
    createdAt: "2026-07-10",
  },
  {
    id: "t7",
    title: "UI Design Updated",
    status: "completed",
    priority: "low",
    labels: ["Design", "Updated"],
    dueDate: "2026-07-31",
    member: "Designer",
    projectId: "p1",
    subtasks: [],
    comments: [],
    createdAt: "2026-07-10",
  },
  {
    id: "t8",
    title: "Security Audit Scheduled",
    status: "completed",
    priority: "high",
    labels: ["Audit", "Scheduled"],
    dueDate: "2026-08-01",
    member: "Security",
    projectId: "p3",
    subtasks: [],
    comments: [],
    createdAt: "2026-07-10",
  },
  {
    id: "t9",
    title: "UI Review",
    status: "on-hold",
    priority: "medium",
    labels: ["Review"],
    member: "Design",
    projectId: "p1",
    subtasks: [],
    comments: [],
    createdAt: "2026-07-05",
  },
  {
    id: "t10",
    title: "Backend Integration",
    status: "on-hold",
    priority: "high",
    labels: ["Development"],
    member: "Dev Team",
    projectId: "p2",
    subtasks: [],
    comments: [],
    createdAt: "2026-07-05",
  },
  {
    id: "t11",
    title: "User Feedback Analysis",
    status: "on-hold",
    priority: "low",
    labels: ["Research"],
    member: "Product",
    projectId: "p1",
    subtasks: [],
    comments: [],
    createdAt: "2026-07-05",
  },
  {
    id: "t12",
    title: "Performance Optimization",
    status: "on-hold",
    priority: "medium",
    labels: ["Optimization"],
    member: "Engineering",
    projectId: "p3",
    subtasks: [],
    comments: [],
    createdAt: "2026-07-05",
  },
];
